### ISSUE TITLE
SamToFastq writes to /dev/stdout  Exception 

### ISSUE THREAD

**Issue by yingwei13mei** [broadinstitute/picard#1851] opened 2023-01-18 09:17 UTC
SamToFastq failed writes to /dev/stdout , and I cannot go on 

### **version(s)**
picard version is 2.20.0 and also tried 2.23.8 

### **Description**
SamToFastq failed writes to /dev/stdout when FASTQ=/dev/stdout. I am working on a light weighted server, try to run the whole GATK pipeline.

### **Expected behavior**
 SamToFastq should write bam file to /dev/stdout on the servers.

### **Behavior**
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/home/edgex/Downloads/cromwell-executions/WholeGenomeGermlineSingleSample/7b7aa126-385a-42c8-b4ca-c1277b9939a3/call-UnmappedBamToAlignedBam/UnmappedBamToAlignedBam/6005fdcf-8e37-4dae-9434-a48b5bd7812d/call-SamToFastqAndBwaMemAndMba/shard-0/tmp.00263bbf
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/home/edgex/Downloads/cromwell-executions/WholeGenomeGermlineSingleSample/7b7aa126-385a-42c8-b4ca-c1277b9939a3/call-UnmappedBamToAlignedBam/UnmappedBamToAlignedBam/6005fdcf-8e37-4dae-9434-a48b5bd7812d/call-SamToFastqAndBwaMemAndMba/shard-0/tmp.00263bbf
INFO	2022-12-07 05:33:24	SamToFastq	

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    SamToFastq -INPUT /home/edgex/Downloads/cromwell-executions/WholeGenomeGermlineSingleSample/7b7aa126-385a-42c8-b4ca-c1277b9939a3/call-UnmappedBamToAlignedBam/UnmappedBamToAlignedBam/6005fdcf-8e37-4dae-9434-a48b5bd7812d/call-SamToFastqAndBwaMemAndMba/shard-0/inputs/-947572082/H06HDADXX130110.1.ATCACGAT.20k_reads.bam -FASTQ /dev/stdout -INTERLEAVE true -NON_PF true
**********

INFO	2022-12-07 05:33:24	MergeBamAlignment	

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    MergeBamAlignment -VALIDATION_STRINGENCY SILENT -EXPECTED_ORIENTATIONS FR -ATTRIBUTES_TO_RETAIN X0 -ATTRIBUTES_TO_REMOVE NM -ATTRIBUTES_TO_REMOVE MD -ALIGNED_BAM /dev/stdin -UNMAPPED_BAM /home/edgex/Downloads/cromwell-executions/WholeGenomeGermlineSingleSample/7b7aa126-385a-42c8-b4ca-c1277b9939a3/call-UnmappedBamToAlignedBam/UnmappedBamToAlignedBam/6005fdcf-8e37-4dae-9434-a48b5bd7812d/call-SamToFastqAndBwaMemAndMba/shard-0/inputs/-947572082/H06HDADXX130110.1.ATCACGAT.20k_reads.bam -OUTPUT H06HDADXX130110.1.ATCACGAT.20k_reads.aligned.unsorted.bam -REFERENCE_SEQUENCE /home/edgex/Downloads/cromwell-executions/WholeGenomeGermlineSingleSample/7b7aa126-385a-42c8-b4ca-c1277b9939a3/call-UnmappedBamToAlignedBam/UnmappedBamToAlignedBam/6005fdcf-8e37-4dae-9434-a48b5bd7812d/call-SamToFastqAndBwaMemAndMba/shard-0/inputs/191116307/Homo_sapiens_assembly38.fasta -PAIRED_RUN true -SORT_ORDER unsorted -IS_BISULFITE_SEQUENCE false -ALIGNED_READS_ONLY false -CLIP_ADAPTERS false -MAX_RECORDS_IN_RAM 2000000 -ADD_MATE_CIGAR true -MAX_INSERTIONS_OR_DELETIONS -1 -PRIMARY_ALIGNMENT_STRATEGY MostDistant -PROGRAM_RECORD_ID bwamem -PROGRAM_GROUP_VERSION 0.7.17-r1188 -PROGRAM_GROUP_COMMAND_LINE bwa mem -K 100000000 -p -v 3 -t 16 -Y /home/edgex/Downloads/cromwell-executions/WholeGenomeGermlineSingleSample/7b7aa126-385a-42c8-b4ca-c1277b9939a3/call-UnmappedBamToAlignedBam/UnmappedBamToAlignedBam/6005fdcf-8e37-4dae-9434-a48b5bd7812d/call-SamToFastqAndBwaMemAndMba/shard-0/inputs/191116307/Homo_sapiens_assembly38.fasta -PROGRAM_GROUP_NAME bwamem -UNMAPPED_READ_STRATEGY COPY_TO_TAG -ALIGNER_PROPER_PAIR_FLAGS true -UNMAP_CONTAMINANT_READS true -ADD_PG_TAG_TO_READS false
**********

05:33:25.209 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/mnt/lustre/genomics/tools/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Wed Dec 07 05:33:25 UTC 2022] MergeBamAlignment ADD_PG_TAG_TO_READS=false UNMAPPED_BAM=/home/edgex/Downloads/cromwell-executions/WholeGenomeGermlineSingleSample/7b7aa126-385a-42c8-b4ca-c1277b9939a3/call-UnmappedBamToAlignedBam/UnmappedBamToAlignedBam/6005fdcf-8e37-4dae-9434-a48b5bd7812d/call-SamToFastqAndBwaMemAndMba/shard-0/inputs/-947572082/H06HDADXX130110.1.ATCACGAT.20k_reads.bam ALIGNED_BAM=[/dev/stdin] OUTPUT=H06HDADXX130110.1.ATCACGAT.20k_reads.aligned.unsorted.bam PROGRAM_RECORD_ID=bwamem PROGRAM_GROUP_VERSION=0.7.17-r1188 PROGRAM_GROUP_COMMAND_LINE=bwa mem -K 100000000 -p -v 3 -t 16 -Y /home/edgex/Downloads/cromwell-executions/WholeGenomeGermlineSingleSample/7b7aa126-385a-42c8-b4ca-c1277b9939a3/call-UnmappedBamToAlignedBam/UnmappedBamToAlignedBam/6005fdcf-8e37-4dae-9434-a48b5bd7812d/call-SamToFastqAndBwaMemAndMba/shard-0/inputs/191116307/Homo_sapiens_assembly38.fasta PROGRAM_GROUP_NAME=bwamem PAIRED_RUN=true CLIP_ADAPTERS=false IS_BISULFITE_SEQUENCE=false ALIGNED_READS_ONLY=false MAX_INSERTIONS_OR_DELETIONS=-1 ATTRIBUTES_TO_RETAIN=[X0] ATTRIBUTES_TO_REMOVE=[NM, MD] EXPECTED_ORIENTATIONS=[FR] ALIGNER_PROPER_PAIR_FLAGS=true SORT_ORDER=unsorted PRIMARY_ALIGNMENT_STRATEGY=MostDistant ADD_MATE_CIGAR=true UNMAP_CONTAMINANT_READS=true UNMAPPED_READ_STRATEGY=COPY_TO_TAG VALIDATION_STRINGENCY=SILENT MAX_RECORDS_IN_RAM=2000000 REFERENCE_SEQUENCE=/home/edgex/Downloads/cromwell-executions/WholeGenomeGermlineSingleSample/7b7aa126-385a-42c8-b4ca-c1277b9939a3/call-UnmappedBamToAlignedBam/UnmappedBamToAlignedBam/6005fdcf-8e37-4dae-9434-a48b5bd7812d/call-SamToFastqAndBwaMemAndMba/shard-0/inputs/191116307/Homo_sapiens_assembly38.fasta    ATTRIBUTES_TO_REVERSE=[OQ, U2] ATTRIBUTES_TO_REVERSE_COMPLEMENT=[E2, SQ] READ1_TRIM=0 READ2_TRIM=0 CLIP_OVERLAPPING_READS=true INCLUDE_SECONDARY_ALIGNMENTS=true MIN_UNCLIPPED_BASES=32 MATCHING_DICTIONARY_TAGS=[M5, LN] VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=2 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Wed Dec 07 05:33:25 UTC 2022] Executing as edgex@camera-emulator on Linux 5.4.0-131-generic amd64; Java HotSpot(TM) 64-Bit Server VM 17.0.5+9-LTS-191; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.20.0-SNAPSHOT
05:33:25.380 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/mnt/lustre/genomics/tools/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Wed Dec 07 05:33:25 UTC 2022] SamToFastq INPUT=/home/edgex/Downloads/cromwell-executions/WholeGenomeGermlineSingleSample/7b7aa126-385a-42c8-b4ca-c1277b9939a3/call-UnmappedBamToAlignedBam/UnmappedBamToAlignedBam/6005fdcf-8e37-4dae-9434-a48b5bd7812d/call-SamToFastqAndBwaMemAndMba/shard-0/inputs/-947572082/H06HDADXX130110.1.ATCACGAT.20k_reads.bam FASTQ=/dev/stdout INTERLEAVE=true INCLUDE_NON_PF_READS=true    OUTPUT_PER_RG=false COMPRESS_OUTPUTS_PER_RG=false RG_TAG=PU RE_REVERSE=true CLIPPING_MIN_LENGTH=0 READ1_TRIM=0 READ2_TRIM=0 INCLUDE_NON_PRIMARY_ALIGNMENTS=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Wed Dec 07 05:33:25 UTC 2022] Executing as edgex@camera-emulator on Linux 5.4.0-131-generic amd64; Java HotSpot(TM) 64-Bit Server VM 17.0.5+9-LTS-191; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.20.0-SNAPSHOT
INFO	2022-12-07 05:33:25	SamAlignmentMerger	Processing SAM file(s): [/dev/stdin]
[Wed Dec 07 05:33:34 UTC 2022] picard.sam.SamToFastq done. Elapsed time: 0.16 minutes.
Runtime.totalMemory()=1048576000
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMException: Error in writing fastq file /dev/stdout
	at htsjdk.samtools.fastq.BasicFastqWriter.write(BasicFastqWriter.java:66)
	at picard.sam.SamToFastq.writeRecord(SamToFastq.java:391)
	at picard.sam.SamToFastq.handleRecord(SamToFastq.java:300)
	at picard.sam.SamToFastq.doWork(SamToFastq.java:192)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
[Wed Dec 07 05:33:35 UTC 2022] picard.sam.MergeBamAlignment done. Elapsed time: 0.18 minutes.
Runtime.totalMemory()=1048576000
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.IllegalArgumentException: Do not use this function to merge dictionaries with different sequences in them. Sequences must be in the same order as well. Found [] and [chr1, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chr10, chr11, chr12, chr13, chr14, chr15, chr16, chr17, chr18, chr19, chr20, chr21, chr22, chrX, chrY, chrM, chr1_KI270706v1_random, chr1_KI270707v1_random, chr1_KI270708v1_random, chr1_KI270709v1_random, chr1_KI270710v1_random, chr1_KI270711v1_random, chr1_KI270712v1_random, ...

For I have checked the input bam file and the directory, and I cannot find any deeper information to dig into this problem. Could you give some suggestion?

**Comment by lbergelson** [comment] 2023-01-19 22:49
@yingwei13mei I'm closing this because we're already discussing it on the forums [the forums](https://gatk.broadinstitute.org/hc/en-us/community/posts/11960801550875-Exception-in-thread-main-java-lang-IllegalArgumentException-Do-not-use-this-function-to-merge-dictionaries-with-different-sequences-in-them-Sequences-must-be-in-the-same-order-as-well?page=1#community_comment_12001753432219) which is the appropriate place

It's hard to tell what the problem is because it's part of a pipeline and it seems to be failing while writing to the pipe but then not failing the job until later.  I think it's more likely that it's an issue with your pipeline / server configuration than it is a picard bug.

My best suggestion right now is to try it with a new version of picard, [2.23.8](https://github.com/broadinstitute/picard/releases/tag/2.23.8) is pretty old and maybe the newest version will work for you.

**Closed by lbergelson** 2023-01-19 22:49 UTC
