### ISSUE TITLE
CollectGCBiasMetrics (as part of CollectMultipleMetrics) ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by DaGaMs** [broadinstitute/picard#1483] opened 2020-03-10 10:11 UTC
### Affected tool(s)
`CollectMultipleMetrics` with `CollectGCBiasMetrics`

### Affected version(s)
- 2.18.4-SNAPSHOT

### Description 
I'm calculating some metrics like this:

```bash
picard CollectMultipleMetrics I=alignment.bam O=CRR035591 R=hg38_full_gatk_HPV_HBV_HCV_EBV.fa.gz DB_SNP=dbsnp_146.hg38.vcf.gz INTERVALS=EBV_hg38.intv PROGRAM=null PROGRAM=CollectSequencingArtifactMetrics PROGRAM=CollectAlignmentSummaryMetrics PROGRAM=CollectInsertSizeMetrics PROGRAM=CollectGcBiasMetrics PROGRAM=QualityScoreDistribution
```

Which causes this error:

```
09:43:56.694 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/gpfs3/apps/htseq/picard-2.18.4/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Tue Mar 10 09:43:56 GMT 2020] CollectMultipleMetrics INPUT=alignment.bam OUTPUT=CRR035591 PROGRAM=[CollectSequencingArtifactMetrics, CollectAlignmentSummaryMetrics, CollectInsertSizeMetrics, CollectGcBiasMetrics, QualityScoreDistribution] INTERVALS=EBV_hg38.intv DB_SNP=dbsnp_146.hg38.vcf.gz REFERENCE_SEQUENCE=hg38_full_gatk_HPV_HBV_HCV_EBV.fa.gz    ASSUME_SORTED=true STOP_AFTER=0 METRIC_ACCUMULATION_LEVEL=[ALL_READS] INCLUDE_UNPAIRED=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Tue Mar 10 09:43:56 GMT 2020] Executing as benjamin@rescomp1.hpc.in.bmrc.ox.ac.uk on Linux 3.10.0-957.10.1.el7.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_45-b14; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.18.4-SNAPSHOT
[Tue Mar 10 09:43:59 GMT 2020] picard.analysis.CollectMultipleMetrics done. Elapsed time: 0.05 minutes.
Runtime.totalMemory()=2058354688
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
        at htsjdk.samtools.util.SequenceUtil.basesEqual(SequenceUtil.java:128)
        at picard.analysis.GcBiasUtils.calculateGc(GcBiasUtils.java:50)
        at picard.analysis.GcBiasUtils.calculateRefWindowsByGc(GcBiasUtils.java:86)
        at picard.analysis.CollectGcBiasMetrics.setup(CollectGcBiasMetrics.java:168)
        at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:129)
        at picard.analysis.CollectMultipleMetrics.doWork(CollectMultipleMetrics.java:426)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:282)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
```
If I remove the `PROGRAM=CollectGcBiasMetrics` then it runs normally. Could this be a regression of #212 ?

**Comment by yfarjoun** [comment] 2020-03-15 17:32
This seems to be due to a bug in htsjdk which was fixed in a later version. but the problem is that somehow your reference array contains a value of -1. I'm not sure how that happened, possibly that's what the N's are turned into...at any rate, if you upgrade to a newer version of picard, this should work better....or at-least give a better error message.

**Closed** 2020-11-03 20:49 UTC
