### ISSUE TITLE
picardtools won't install using gradle on Ubuntu 14.04

### ISSUE THREAD

**Issue by banridire** [broadinstitute/picard#640] opened 2016-08-30 23:04 UTC
I looked at a previous post with a similar problem. But the solution does not work here.
Linux 14.04:
git clone -b 2.6.0 --depth 1 git@github.com:broadinstitute/picard.git
cd  picard
java -version
java version "1.8.0_20"
Java(TM) SE Runtime Environment (build 1.8.0_20-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.20-b23, mixed mode)

./gradlew shadowJar --stacktrace --debug >> picard.txt 2>&1

[picard.txt](https://github.com/broadinstitute/picard/files/446086/picard.txt)

Thanks for any input,
Terri Knight

**Comment by lbergelson** [comment] 2016-09-02 15:55
@banridire Hi Terri.  I'm sorry you're having trouble and thank you for the detailed log.  

From a quick look at it I haven't yet been able to understand what the problem is. 

My suggestion for now is to use the [prebuilt jar](https://github.com/broadinstitute/picard/releases/download/2.6.0/picard.jar) if you can. 

My only other off the cuff suggestion is that you might try updating your Java version.  1.8.0_20 is a pretty old build java 8.  I don't know specifically if that's the problem, but I know in GATK we had issues with early java 8 builds that were resolved by moving to more recent ones.  

I'll have a chance to take a deeper look at this when I'm back in the office after labor day.  Sorry for the slow response.

**Comment by jeremycfd** [comment] 2016-09-19 16:16
I similarly have been unable to install Picard on Ubuntu 14.04.5 LTS.

**Comment by lbergelson** [comment] 2016-09-19 18:09
Sorry, I've been unable to get a change to help with this.  Hopefully someone else on the team will be able to debug these errors. ( @yfarjoun can you point someone at this?)  In the meantime I recommend using the prebuilt jars if that's possible.  

We run our test builds on travis which uses 14.04 LTS as its base image, so there shouldn't be anything fundamental preventing it from working.

**Comment by nh13** [comment] 2016-09-19 19:28
I did some googling and saw that I had a similar error message previously since my links were purple, and I remembered that I updated my java version (to `1.8.0_91`) and the issue when away.  I have a vague recollection that it could also be related to java not being properly installed, which that would have also fixed.  Could you try updating your java version?

**Comment by vdauwera** [comment] 2017-01-18 21:56
Closing since the OP has not responded to questions.

**Closed by vdauwera** 2017-01-18 21:56 UTC
