### ISSUE TITLE
Command Line Overview repeated itself 4 times

### ISSUE THREAD

**Issue by JohnMCMa** [broadinstitute/picard#674] opened 2016-10-14 14:15 UTC
I have noticed the tool-specific documentations in the [Command Line Overview](http://broadinstitute.github.io/picard/command-line-overview.html) seems to have repeated itself 4 times.

**Comment by vdauwera** [comment] 2016-10-14 14:26
We've noticed that too -- this has appeared then gone away then reappeared depending on the release, with different repeat counts each time. I'm pretty sure it's a technical glitch in the generation of the documents but right now we don't have time to hunt down the cause.

**Comment by droazen** [comment] 2016-10-17 22:03
I've fixed this -- closing.

**Comment by droazen** [comment] 2016-10-17 22:04
(Fixed by following the official release instructions for Picard here: https://github.com/broadinstitute/picard/wiki/How-to-release-Picard)

**Closed by droazen** 2016-10-17 22:03 UTC
