### ISSUE TITLE
Duplicates missed when mate has low mapping quality

### ISSUE THREAD

**Issue by yfarjoun** [broadinstitute/picard#128] opened 2014-12-18 05:01 UTC
When a pair-end read has one read with good mapping quality and the second with low (e.g. 0) mapping quality, the second may be placed in several locations randomly according to the aligner (even with the same aligner). This means that a duplicated such fragment will be incorrectly _not_ marked as duplicate if the two version of the second read are aligned differently (note that this has nothing to do with secondary or supplemental alignments)

Perhaps the solution could be as simple as to add another condition to line 283 in MarkDuplicates.java (and perhaps a similar condition in MarkDuplicatesWithCigar?) that verifies that the mate is well mapped. I suspect that a MQ!=0 would suffice, though it depends on the aligner...so perhaps it could be an @Option.

**Comment by yfarjoun** [comment] 2015-01-06 21:32
@eitanbanks ran a foghorn implementation of MarkDuplicates tool that uses (a Fourier transform of) the 5' end sequences to identify the fragments. He reports that this resolves the problem described here. This presents two possibilities (as I see it):

1. Convert Picard to be sequence based rather that alignment based (large change in the way things work, but consistent)
1. Add an option that when a read has low MQ, the sequence is used rather than the alignment (much less disruptive, but less consistent) 

It should be said that this problem presents mainly in low-complexity, high depth samples which are not something we are promoting...so this points to the second solution since it would entail minimal disruption and presumably be less time-consuming.

**Comment by bhandsaker** [comment] 2015-01-06 21:42
If you are planning to change the behavior of MarkDuplicates, I would 
ideally like the chance to be able to test how it affects CNV calling 
(it may improve things).
Any chance you could implement this as an option and, ideally, help me 
locate or create a data set (ideally with many samples) with MD run both 
ways that I could evaluate?
Also, we should make sure that any bams are clearly marked as to which 
method is used.
It is quite possible that mixing bams with the two methodologies in 
joint CNV calling could create batch effects that would be difficult to 
overcome post-hoc.

-Bob

**Comment by yfarjoun** [comment] 2015-02-09 18:49
This issue also seems to come up in samples with high chimeric rates, some
of the reads are unmapped and their mates are not properly marked as
duplicates, though looking at IGV, they seem to be.

The screen shot is from sample
/seq/picard_aggregation/G77386/J14VAN304/current/J14VAN304.bam,
location 1:34,233,037-34,234,268

Yossi.

**Comment by nh13** [comment] 2015-03-06 19:40
@yfarjoun should we be posting file paths here?

**Comment by pmBarlev** [comment] 2015-11-19 07:24
@yfarjoun I have a bam with two chimeric read pairs in which:
1. Both reads in both pairs have mapping quality 0.
2. Both reads in both pairs are aligned the same.
3. They are not marked as duplicates.

This doesn't quite the fit the bill of the bug you describe above (since both reads do align the same), but seems related. Do you know why this happens?

I'm attaching the relevant portion of the .bam:
```
@PG	ID:GATK IndelRealigner	CL:knownAlleles=[] targetIntervals=/bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/MUTECT_SC_N_VS_C_20151026_B37/GATK/DF109EBF-AEE9-D348-9C72-BF958C37ABB9.RealignTarget.list LODThresholdForCleaning=0.4 consensusDeterminationModel=USE_READS entropyThreshold=0.15 maxReadsInMemory=150000 maxIsizeForMovement=3000 maxPositionalMoveAllowed=200 maxConsensuses=30 maxReadsForConsensuses=120 maxReadsForRealignment=20000 noOriginalAlignmentTags=false nWayOut=null generate_nWayOut_md5s=false check_early=false noPGTag=false keepPGTags=false indelsFileForDebugging=null statisticsFileForDebugging=null SNPsFileForDebugging=null
@PG	ID:GATK IndelRealigner.1	CL:knownAlleles=[] targetIntervals=/bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/MUTECT_SC_N_VS_C_20151026_B37/GATK/2FE1A718-FD4C-0546-B3F7-7FF35964E264.RealignTarget.list LODThresholdForCleaning=0.4 consensusDeterminationModel=USE_READS entropyThreshold=0.15 maxReadsInMemory=150000 maxIsizeForMovement=3000 maxPositionalMoveAllowed=200 maxConsensuses=30 maxReadsForConsensuses=120 maxReadsForRealignment=20000 noOriginalAlignmentTags=false nWayOut=null generate_nWayOut_md5s=false check_early=false noPGTag=false keepPGTags=false indelsFileForDebugging=null statisticsFileForDebugging=null SNPsFileForDebugging=null
@PG	ID:GATK IndelRealigner.2	CL:knownAlleles=[] targetIntervals=/bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/MUTECT_SC_N_VS_C_20151026_B37/GATK/47242324-DECD-3049-ABB4-CEE5FD1EB788.RealignTarget.list LODThresholdForCleaning=0.4 consensusDeterminationModel=USE_READS entropyThreshold=0.15 maxReadsInMemory=150000 maxIsizeForMovement=3000 maxPositionalMoveAllowed=200 maxConsensuses=30 maxReadsForConsensuses=120 maxReadsForRealignment=20000 noOriginalAlignmentTags=false nWayOut=null generate_nWayOut_md5s=false check_early=false noPGTag=false keepPGTags=false indelsFileForDebugging=null statisticsFileForDebugging=null SNPsFileForDebugging=null
@PG	ID:GATK IndelRealigner.3	CL:knownAlleles=[] targetIntervals=/bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/MUTECT_SC_N_VS_C_20151026_B37/GATK/441CF955-45F0-E04C-9761-6F44CE08ECF9.RealignTarget.list LODThresholdForCleaning=0.4 consensusDeterminationModel=USE_READS entropyThreshold=0.15 maxReadsInMemory=150000 maxIsizeForMovement=3000 maxPositionalMoveAllowed=200 maxConsensuses=30 maxReadsForConsensuses=120 maxReadsForRealignment=20000 noOriginalAlignmentTags=false nWayOut=null generate_nWayOut_md5s=false check_early=false noPGTag=false keepPGTags=false indelsFileForDebugging=null statisticsFileForDebugging=null SNPsFileForDebugging=null
@PG	ID:GATK PrintReads	VN:3.3-0-g37228af	CL:readGroup=null platform=null number=-1 sample_file=[] sample_name=[] simplify=false no_pg_tag=false
@PG	ID:MarkDuplicates	PN:MarkDuplicates	VN:1.115(30b1e546cc4dd80c918e151dbfe46b061e63f315_1402927010)	CL:picard.sam.MarkDuplicates INPUT=[/bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/CutadaptFastq4PPLall/bam/SC241_WS4N_GCCAAT_L001.bam] OUTPUT=/bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/CutadaptFastq4PPLall/markedBam/SC241_WS4N_GCCAAT_L001_marked.bam METRICS_FILE=/bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/CutadaptFastq4PPLall/markedBam/SC241_WS4N_GCCAAT_L001_metrics.txt    PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates REMOVE_DUPLICATES=false ASSUME_SORTED=false MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 READ_NAME_REGEX=[a-zA-Z0-9]+:[0-9]:([0-9]+):([0-9]+):([0-9]+).* OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
@PG	ID:MarkDuplicates.5	PN:MarkDuplicates	VN:1.115(30b1e546cc4dd80c918e151dbfe46b061e63f315_1402927010)	CL:picard.sam.MarkDuplicates INPUT=[/bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/CutadaptFastq4PPLall/bam/SC241_WS4N_GCCAAT_L002.bam] OUTPUT=/bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/CutadaptFastq4PPLall/markedBam/SC241_WS4N_GCCAAT_L002_marked.bam METRICS_FILE=/bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/CutadaptFastq4PPLall/markedBam/SC241_WS4N_GCCAAT_L002_metrics.txt    PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates REMOVE_DUPLICATES=false ASSUME_SORTED=false MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 READ_NAME_REGEX=[a-zA-Z0-9]+:[0-9]:([0-9]+):([0-9]+):([0-9]+).* OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
@PG	ID:MarkDuplicates.6	PN:MarkDuplicates	VN:1.115(30b1e546cc4dd80c918e151dbfe46b061e63f315_1402927010)	CL:picard.sam.MarkDuplicates INPUT=[/bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/CutadaptFastq4PPLall/bam/SC241_WS4N_GCCAAT_L003.bam] OUTPUT=/bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/CutadaptFastq4PPLall/markedBam/SC241_WS4N_GCCAAT_L003_marked.bam METRICS_FILE=/bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/CutadaptFastq4PPLall/markedBam/SC241_WS4N_GCCAAT_L003_metrics.txt    PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates REMOVE_DUPLICATES=false ASSUME_SORTED=false MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 READ_NAME_REGEX=[a-zA-Z0-9]+:[0-9]:([0-9]+):([0-9]+):([0-9]+).* OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
@PG	ID:MarkDuplicates.7	PN:MarkDuplicates	VN:1.115(30b1e546cc4dd80c918e151dbfe46b061e63f315_1402927010)	CL:picard.sam.MarkDuplicates INPUT=[/bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/CutadaptFastq4PPLall/bam/SC241_WS4N_GCCAAT_L004.bam] OUTPUT=/bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/CutadaptFastq4PPLall/markedBam/SC241_WS4N_GCCAAT_L004_marked.bam METRICS_FILE=/bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/CutadaptFastq4PPLall/markedBam/SC241_WS4N_GCCAAT_L004_metrics.txt    PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates REMOVE_DUPLICATES=false ASSUME_SORTED=false MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 READ_NAME_REGEX=[a-zA-Z0-9]+:[0-9]:([0-9]+):([0-9]+):([0-9]+).* OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
@PG	ID:MarkDuplicates.9	PN:MarkDuplicates	PP:MarkDuplicates.7	VN:1.115(30b1e546cc4dd80c918e151dbfe46b061e63f315_1402927010)	CL:picard.sam.MarkDuplicates INPUT=[/bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/CutadaptFastq4PPLall/alignBqsr/SC241_WS4N_GCCAAT_L001_marked_align_bqsr.bam, /bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/CutadaptFastq4PPLall/alignBqsr/SC241_WS4N_GCCAAT_L002_marked_align_bqsr.bam, /bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/CutadaptFastq4PPLall/alignBqsr/SC241_WS4N_GCCAAT_L003_marked_align_bqsr.bam, /bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/CutadaptFastq4PPLall/alignBqsr/SC241_WS4N_GCCAAT_L004_marked_align_bqsr.bam] OUTPUT=/bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/SC241_WS4N.bam METRICS_FILE=/bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/SC241_WS4N_metrics.txt    PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates REMOVE_DUPLICATES=false ASSUME_SORTED=false MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 READ_NAME_REGEX=[a-zA-Z0-9]+:[0-9]:([0-9]+):([0-9]+):([0-9]+).* OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
@PG	ID:MarkDuplicates.A	PN:MarkDuplicates	PP:MarkDuplicates.6	VN:1.115(30b1e546cc4dd80c918e151dbfe46b061e63f315_1402927010)	CL:picard.sam.MarkDuplicates INPUT=[/bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/CutadaptFastq4PPLall/alignBqsr/SC241_WS4N_GCCAAT_L001_marked_align_bqsr.bam, /bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/CutadaptFastq4PPLall/alignBqsr/SC241_WS4N_GCCAAT_L002_marked_align_bqsr.bam, /bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/CutadaptFastq4PPLall/alignBqsr/SC241_WS4N_GCCAAT_L003_marked_align_bqsr.bam, /bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/CutadaptFastq4PPLall/alignBqsr/SC241_WS4N_GCCAAT_L004_marked_align_bqsr.bam] OUTPUT=/bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/SC241_WS4N.bam METRICS_FILE=/bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/SC241_WS4N_metrics.txt    PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates REMOVE_DUPLICATES=false ASSUME_SORTED=false MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 READ_NAME_REGEX=[a-zA-Z0-9]+:[0-9]:([0-9]+):([0-9]+):([0-9]+).* OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
@PG	ID:MarkDuplicates.B	PN:MarkDuplicates	PP:MarkDuplicates.5	VN:1.115(30b1e546cc4dd80c918e151dbfe46b061e63f315_1402927010)	CL:picard.sam.MarkDuplicates INPUT=[/bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/CutadaptFastq4PPLall/alignBqsr/SC241_WS4N_GCCAAT_L001_marked_align_bqsr.bam, /bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/CutadaptFastq4PPLall/alignBqsr/SC241_WS4N_GCCAAT_L002_marked_align_bqsr.bam, /bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/CutadaptFastq4PPLall/alignBqsr/SC241_WS4N_GCCAAT_L003_marked_align_bqsr.bam, /bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/CutadaptFastq4PPLall/alignBqsr/SC241_WS4N_GCCAAT_L004_marked_align_bqsr.bam] OUTPUT=/bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/SC241_WS4N.bam METRICS_FILE=/bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/SC241_WS4N_metrics.txt    PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates REMOVE_DUPLICATES=false ASSUME_SORTED=false MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 READ_NAME_REGEX=[a-zA-Z0-9]+:[0-9]:([0-9]+):([0-9]+):([0-9]+).* OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
@PG	ID:MarkDuplicates.C	PN:MarkDuplicates	PP:MarkDuplicates	VN:1.115(30b1e546cc4dd80c918e151dbfe46b061e63f315_1402927010)	CL:picard.sam.MarkDuplicates INPUT=[/bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/CutadaptFastq4PPLall/alignBqsr/SC241_WS4N_GCCAAT_L001_marked_align_bqsr.bam, /bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/CutadaptFastq4PPLall/alignBqsr/SC241_WS4N_GCCAAT_L002_marked_align_bqsr.bam, /bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/CutadaptFastq4PPLall/alignBqsr/SC241_WS4N_GCCAAT_L003_marked_align_bqsr.bam, /bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/CutadaptFastq4PPLall/alignBqsr/SC241_WS4N_GCCAAT_L004_marked_align_bqsr.bam] OUTPUT=/bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/SC241_WS4N.bam METRICS_FILE=/bio/projects/Sheba/MayaDadiani/Data/Mutect_SC_N_vs_C_20151026_B37/libs/SC241_WS4N/SC241_WS4N_metrics.txt    PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates REMOVE_DUPLICATES=false ASSUME_SORTED=false MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 READ_NAME_REGEX=[a-zA-Z0-9]+:[0-9]:([0-9]+):([0-9]+):([0-9]+).* OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
HISEQ:99:C6W0CACXX:2:2213:16816:19878	337	1	10000	0	52H48M	6	160131968	0	ATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACC	=>==>>>=<<==>=;;===<::==<;::<<=;::==?>====>><;==	SA:Z:6,160132336,-,58M42S,0,0;	BD:Z:IHHJHKKHHJHKKHHJHKKHHJHKKHHJHKKHHKILLIJLKOOLHJGG	PG:Z:MarkDuplicates.B	RG:Z:CutadaptFastq4PPLall_L002	BI:Z:LLKNJLNKJMIKMKJMIKMKJMIKMKJMIKMKJMIKMKKNJMPNKNJJ	NM:i:0	AS:i:48	XS:i:47
HISEQ:99:C6W0CACXX:3:2103:10975:91079	337	1	10000	0	52H48M	6	160131968	0	ATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACC	=<===>>;<<==>;<3=<=:;;88<:::;3<;:;;=?>====>9<;==	SA:Z:6,160132336,-,58M42S,0,0;	BD:Z:IHHJHKKHHJHKKHHJHKKHHJHKKHHJHKKHHKILLIJLKOOLHJGG	PG:Z:MarkDuplicates.A	RG:Z:CutadaptFastq4PPLall_L003	BI:Z:LLKMJKNKJLIKMKJLIKMKJLIKMKJLIKMKJLIKNKKMJMPNKMJJ	NM:i:0	AS:i:48	XS:i:47

```

**Comment by yfarjoun** [comment] 2015-11-19 12:09
I see that the records are from different readgroups. Could you include
their @RG tags as well? I want to see if they are from the same library or
not.

Also, could you send the mates? I'd like to see the 5' end of their
alignment.

**Comment by pmBarlev** [comment] 2015-11-19 12:54
Perhaps the issue is that these reads are not primary alignments (see line 148 in MarkDuplicates.java)? Indeed, both the corresponding primary alignments and their mates are marked as duplicates.

In any case, here are the read groups:
```
@RG	ID:CutadaptFastq4PPLall_L001	PL:illumina	PU:GCCAAT	LB:SC241_WS4N	SM:SC241_WS4N
@RG	ID:CutadaptFastq4PPLall_L002	PL:illumina	PU:GCCAAT	LB:SC241_WS4N	SM:SC241_WS4N
@RG	ID:CutadaptFastq4PPLall_L003	PL:illumina	PU:GCCAAT	LB:SC241_WS4N	SM:SC241_WS4N
@RG	ID:CutadaptFastq4PPLall_L004	PL:illumina	PU:GCCAAT	LB:SC241_WS4N	SM:SC241_WS4N
```

Here are the mates:

```
HISEQ:99:C6W0CACXX:2:2213:16816:19878	1185	6	160131968	0	91M9S	=	160132336	426	CATAACCACCACTCACACTGCTCTGACCTCCATAACCACCTCCATAACCACCACTCACACTGCTCTGACCTCCATAACCACCTCCATAACCCTAACCCTA	:97::998:;9;:;:;:;;<;;<<=<<====<=>?>>=>>>>?>?@@??>??<>?>=>=>>?>>>>?<<<;<<:;<<<<:<<;<<;;==<==<==<:98;	MC:Z:58M42S	BD:Z:GGJIKKLJHJIGIFGGFGIJJJFFJJJJIGJJJIHIJJHJIGJJJIHIJJHJJHJGHHGHJKKKGGKKJJIGJJJIHIJJHJIHKKKJIKLJLMKLJHIJ	PG:Z:MarkDuplicates.B	RG:Z:CutadaptFastq4PPLall_L002	BI:Z:JJMLGJJJHIJHIEHHHIJLLLFILMJJKGILMLHKKLJKKGILMLHKKLJKLJKGJJJJKMMMGJMNJKKGILMLHKKLJKKGIMNMILLLLMJMKJKL	NM:i:0	MQ:i:0	AS:i:91	XS:i:91
HISEQ:99:C6W0CACXX:3:2103:10975:91079	1185	6	160131968	0	91M9S	=	160132336	426	CATAACCACCACTCACAATGCTCTGACCTCCATAACCACCTCCATAACCACCACTCACACTGCTCTGACCTCCATAACCACCTCCATAACCCTAACCCTA	997::8989;9::;:8:*8;99;<=<:<===<==?>>==>>>?>?@>??>=><=>>=>=>>?>>>>?>;<;<<:;:<;;:;;;;;:;:<;;;;:<;8789	MC:Z:58M42S	BD:Z:GGJIKKKJHJIGIFGGFGGJJJFFJJIIIGJJJIHIJJHJIGJJJIHIJJHJJHJGHHGHJKKKGGKKJJIGJJJIHIJJHJJHKKKJIJLJLMKLJHIJ	PG:Z:MarkDuplicates.A	RG:Z:CutadaptFastq4PPLall_L003	BI:Z:JJMLGJKJHJJHIEHHIIILLLFILMJKJFILLLHKLLJLKGILMLHKLLJLLJKGJJJJKMMMGJMMJLJGILMLHKLLJLKGIMNMILMKLMJMLJKL	NM:i:1	MQ:i:0	AS:i:86	XS:i:86


```

And the primary alignments

```
HISEQ:99:C6W0CACXX:2:2213:16816:19878	1105	6	160132336	0	58M42S	=	160131968	-426	AACCACCTCCATAACCACCACTCACACTGCTCTGACCTCCATAACCACCTCCATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACC	:97:6<=<<=<2;5<=<<=;>=><?=@<>@>>=?<?@=?@>?>>?@>?@??@=>==>>>=<<==>=;;===<::==<;::<<=;::==?>====>><;==	SA:Z:1,10000,-,52S48M,0,0;	MC:Z:91M9S	BD:Z:HJJHNNMMLMKJJKKIKKILKLIIHKKKLJIKHKJKJJJKIHHJJHJKJJJKIHHJHKKHHJHKKHHJHKKHHJHKKHHJHKKHHKILLIJLKOOLHJGG	PG:Z:MarkDuplicates.B	RG:Z:CutadaptFastq4PPLall_L002	BI:Z:KNLKPNMNNONMLOMLOMLMMOLLLMNNOMKNJNNLLLLMLLKNLKNLLLLMLLKNJLNKJMIKMKJMIKMKJMIKMKJMIKMKJMIKMKKNJMPNKNJJ	NM:i:0	MQ:i:0	AS:i:58	XS:i:58
HISEQ:99:C6W0CACXX:3:2103:10975:91079	1105	6	160132336	0	58M42S	=	160131968	-426	AACCACCTCCATAACCACCACTCACACTGCTCTGACCTCCATAACCACCTCCATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACC	797:6<=<>=9980<<;:;5<<<67/><;4*==::?@???;)<>?@>>@2??=<===>>;<<==>;<3=<=:;;88<:::;3<;:;;=?>====>9<;==	SA:Z:1,10000,-,52S48M,0,0;	MC:Z:91M9S	BD:Z:HJJHNNMMLMKJIKKIKKILKLIIHKKKLJIKHKJKJJJKIHHJJHJKJJJKIHHJHKKHHJHKKHHJHKKHHJHKKHHJHKKHHKILLIJLKOOLHJGG	PG:Z:MarkDuplicates.A	RG:Z:CutadaptFastq4PPLall_L003	BI:Z:KMLKONMNNONMLNMLNMLMMOLLLMNNOMLNKMNLLMLMLLKMLKMLLLLMLLKMJKNKJLIKMKJLIKMKJLIKMKJLIKMKJLIKNKKMJMPNKMJJ	NM:i:0	MQ:i:0	AS:i:58	XS:i:58

```

**Comment by yfarjoun** [comment] 2015-11-19 14:19
That indeed seems to be the issue. (the secondary alignements)

**Comment by vdauwera** [comment] 2017-01-19 02:11
This thread being well over a year, I'm closing it. Resurrect it if this is still a thing.

**Closed by vdauwera** 2017-01-19 02:11 UTC
Labels: bug
