### ISSUE TITLE
ERROR StatusLogger No log4j2 configuration file found

### ISSUE THREAD

**Issue by splaisan** [broadinstitute/picard#890] opened 2017-08-03 09:00 UTC
Dear,

After wrapping picard2 (v10.6) into Genepattern, each **successful** run returns a stderr due to the 'log4j2 configuration file found'. 
When I run the same Picard jar under terminal on the same server, I do also get the error but in terminal this is not an issue as stderr does not trigger behaviour as in GP.

Is this a message linked to the latest 10.6 version?

my Genepattern command is of the form:

`commandLine=\ <java> <java_flags> -jar <picard-tools-2>/picard.jar CollectMultipleMetrics I\=<input.file> O\=<output_prefix> <program> <reference> VALIDATION_STRINGENCY\=<stringency> VERBOSITY\=<verbosity>`

How can I prevent this besides silencing the errors (I want to retain real runtime errors)?

Thanks in advance
Stephane
```
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
[Thu Aug 03 10:18:21 CEST 2017] picard.analysis.CollectMultipleMetrics INPUT=/opt/tools/GenePatternServer/jobResults/340/NA18507-10pc_sample_coord-srt.sorted.bam OUTPUT=QC_metrics_NA18507-10pc_sample_coord-srt.sorted PROGRAM=[CollectAlignmentSummaryMetrics] VALIDATION_STRINGENCY=LENIENT    ASSUME_SORTED=true STOP_AFTER=0 METRIC_ACCUMULATION_LEVEL=[ALL_READS] INCLUDE_UNPAIRED=false VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Thu Aug 03 10:18:21 CEST 2017] Executing as genepattern@MAF-SRV-04 on Linux 3.13.0-123-generic amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_131-b11; Deflater: Jdk; Inflater: Jdk; Picard version: 2.10.6-SNAPSHOT
INFO	2017-08-03 10:18:31	SinglePassSamProgram	Processed     1,000,000 records.  Elapsed time: 00:00:09s.  Time for last 1,000,000:    9s.  Last read position: chr21:36,379,733
[Thu Aug 03 10:18:35 CEST 2017] picard.analysis.CollectMultipleMetrics done. Elapsed time: 0.27 minutes.
Runtime.totalMemory()=2595749888
```

**Comment by ktibbett** [comment] 2017-08-03 09:56
Closing as a duplicate of [883|https://github.com/broadinstitute/picard/issues/883]

**Closed by ktibbett** 2017-08-03 09:56 UTC
