### ISSUE TITLE
Possible bug in LiftoverVcf

### ISSUE THREAD

**Issue by dekling** [broadinstitute/picard#471] opened 2016-03-02 19:45 UTC
User raised issue that his/her data returned the ERROR:LiftoverVcf  Encountered a contig, chr1 that is not part of the target reference.

I attempted to troubleshoot using most recent version of the jar file (2.1.0) on my local drive and tested multiple vcfs.  I consistently encountered the same type of error.

Moreover, I ran this tool back in August 2015 on Picard version 1.137 and it worked fine.

I loaded test files onto the server to troubleshoot.  However, when running the tool on the server, I get yet a different type of error: Exception in thread "main" java.lang.NullPointerException

Here is the test script for the server:

-bash:gsa3:/humgen/gsa-scr1/dkling 739 $ java -jar picard.jar LiftoverVcf I=/humgen/gsa-scr1/dkling/vcf/HQ_snippet_a.vcf O=/humgen/gsa-scr1/dkling/vcf/LO_test.vcf CHAIN=/humgen/gsa-scr1/dkling/vcf/b37tohg19.chain REJECT=/humgen/gsa-scr1/dkling/vcf/reject.vcf R=/humgen/gsa-scr1/pub/bundle/2.8/hg19/ucsc.hg19.fasta.gz

Thank you in advance,

-David

**Comment by yfarjoun** [comment] 2016-05-18 03:50
@dekling is this still considered a bug?

**Comment by dekling** [comment] 2016-05-18 11:05
I will test it on the latest version.

**Comment by dekling** [comment] 2016-05-18 19:36
Still generates Exception in thread "main" java.lang.NullPointerException.  Ran this on Picard 2.2.4.

**Comment by fleharty** [comment] 2016-05-18 19:43
@dekling Could you send me the exact command line you run, I think I should have the files.

**Comment by dekling** [comment] 2016-05-18 19:44
Sure:
java -jar picard.jar LiftoverVcf I=/humgen/gsa-scr1/dkling/vcf/HQ_snippet_a.vcf O=/humgen/gsa-scr1/dkling/vcf/LO_test.vcf CHAIN=/humgen/gsa-scr1/dkling/vcf/b37tohg19.chain REJECT=/humgen/gsa-scr1/dkling/vcf/reject.vcf R=/humgen/gsa-scr1/pub/bundle/2.8/hg19/ucsc.hg19.fasta.gz

**Comment by dylkot** [comment] 2017-08-24 11:55
I still have this same bug:

**Specs**: 

Java HotSpot(TM) 64-Bit Server VM 1.8.0_144-b01; Picard version: 2.7.1

**Cmd:**

java -Xmx4000m -jar path_to_picard/picard.jar LiftoverVcf INPUT=path_to_vcf.vcf C=../Chain/hg19ToHg38.over.chain.gz O=../GRCh38/path_to_vcf.vcf REJECT=../FGRCh38/rejected.vcf R=../../GRCh38_Fa/GRCh38.d1.vd1.fa

**Error:**

[Thu Aug 24 11:52:42 UTC 2017] Executing as root@master on Linux 3.2.0-39-virtual amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_144-b01; Picard version: 2.7.1-SNAPSHOT
INFO	2017-08-24 11:52:42	LiftoverVcf	Loading up the target reference genome.
[Thu Aug 24 11:52:42 UTC 2017] picard.vcf.LiftoverVcf done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=145227776
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.NullPointerException
	at picard.vcf.LiftoverVcf.doWork(LiftoverVcf.java:158)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:208)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)

Originally the vcf did not have chr before the chromosomes but I edited the file to have this so it would match the fa and the chain file.

**Comment by fleharty** [comment] 2017-08-24 13:44
@dylkot Could you provide the input files that you use to generate this error?

**Comment by yfarjoun** [comment] 2017-08-24 14:06
Please try with the latest release as the line numbers in your error
message do not make much sense.

**Comment by yfarjoun** [comment] 2017-12-28 01:00
closing due to lack of interest. There has been much progress in LiftOver in the past few months. please reopen if this is still an issue.

**Comment by basti3333** [comment] 2018-01-15 13:18
Can you please reopen this bug? I still get an error using the latest picard version:

**Error:**
 [Mon Jan 15 08:03:19 EST 2018] LiftoverVcf INPUT=293_CG.vcf OUTPUT=293_CG.hg19.vcf CHAIN=hg18ToHg19.over.chain REJECT=293_CG.hg19_rejected.vcf REFERENCE_SEQUENCE=/home/basti/genomes/human/GRCh37/fasta/GRCh37_hg19.fasta    WARN_ON_MISSING_CONTIG=false WRITE_ORIGINAL_POSITION=false LIFTOVER_MIN_MATCH=1.0 ALLOW_MISSING_FIELDS_IN_HEADER=false TAGS_TO_REVERSE=[AF] TAGS_TO_DROP=[MAX_AF] VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Mon Jan 15 08:03:19 EST 2018] Executing as basti@pegasus2 on Linux 4.4.0-104-generic amd64; OpenJDK 64-Bit Server VM 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12; Deflater: Intel; Inflater: Intel; Picard version: 2.17.3-SNAPSHOT
INFO    2018-01-15 08:03:20     LiftoverVcf     Loading up the target reference genome.
[Mon Jan 15 08:03:20 EST 2018] picard.vcf.LiftoverVcf done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=2058354688
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.NullPointerException
        at picard.vcf.LiftoverVcf.doWork(LiftoverVcf.java:263)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:269)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:98)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:108)

**vcf file:**
bioinformatics.psb.ugent.be/downloads/genomeview/hek293/SNP/293_CG.vcf.gz

**chain file:**
http://hgdownload.cse.ucsc.edu/goldenPath/hg18/liftOver/hg18ToHg19.over.chain.gz

**Cmd:**
java -jar  /home/basti/bin/picard/picard.jar   LiftoverVcf I=293_CG.vcf O=293_CG.hg19.vcf CHAIN=hg18ToHg19.over.chain REJECT=293_CG.hg19_rejected.vcf R=/home/basti/genomes/human/GRCh37/fasta/GRCh37_hg19.fasta

**java version:**
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

**Comment by merceneryinbox** [comment] 2018-02-16 08:32
Is it possible to share the link to input files - to look at your input files except .fasta?

**Comment by yfarjoun** [comment] 2018-02-21 20:27
can't reproduce. Seems to work fine in 2.17.10 (the version I have installed)

**Closed** 2018-02-21 20:28 UTC
Labels: bug

**Comment by merceneryinbox** [comment] 2018-03-13 08:22
It seems like insufficiently information(in exception throwing messages) about what it is about and how exactly it must be resolved as you can see at this similar issues like this :  https://github.com/broadinstitute/picard/issues/1136#issuecomment-372477867
I'll add some useful messages in TribbleExceptions if you do not mind.
