### ISSUE TITLE
Add a license file to the top level of the Picard repo

### ISSUE THREAD

**Issue by stevendavis** [broadinstitute/picard#764] opened 2017-03-01 15:48 UTC
### Tool(s) involved
Picard

### Description 
Please add a license file to the top level of the Picard repo.

**Comment by sooheelee** [comment] 2017-03-01 16:40
Hi @stevendavis can you tell me which type of license we should use? Thanks.

**Comment by stevendavis** [comment] 2017-03-01 16:55
Hi @sooheelee, thanks for the prompt reply.  As far as I know, Picard is licensed with the MIT license.  You can find it here:  https://opensource.org/licenses/MIT

The source files in your repo already have a license notice, but it is helpful to have a separate license file in the top level of the repo.  I suggest adding a license file called "LICENSE.TXT".

**Comment by vdauwera** [comment] 2017-03-01 17:06
I think we already have an issue for this. There was some discussion that the situation is more complicated because some source files have difference license -- iirc the conclusion was that Picard is "MIT unless otherwise specified".

**Comment by sooheelee** [comment] 2017-03-01 17:36
Does the "unless otherwise specified" line need to be in the top-level license itself or can it be stated in the `.md` readme on the landing page for the repo? 

I'm interested in following-up on this so @vdauwera, can you point me to the other issue?

**Comment by vdauwera** [comment] 2017-03-01 18:15
It's only a vague recollection, I don't have a url for this. If I'm not wrong it should come up in an issue search for "license".

Yes, the "otherwise specified" line should be in the top-level license. If we provide such a file, it should contain all the information a person would need to understand the overall licensing situation without needing to read anything else.

**Comment by sooheelee** [comment] 2017-03-01 19:23
The issue is <https://github.com/broadinstitute/picard/issues/442>. To avoid redundancy, I will close this later issue. Please followup in #422 @stevendavis.

**Closed by sooheelee** 2017-03-01 19:23 UTC
