### ISSUE TITLE
picard SortVcf I=file.vcf O=- should exit immediately

### ISSUE THREAD

**Issue by mmokrejs** [broadinstitute/picard#762] opened 2017-02-23 21:30 UTC
Hi,
  I thought I may do:

`picard SortVcf I=file.vcf O=- | less`

but it does all the scanning of input file and after reading all the input it realizes it is not going to write the sorted result file. Please verify commandline arguments immediately after startup and do not waste resources.

The command exited at the with:

```
[Thu Feb 23 22:28:12 CET 2017] picard.vcf.SortVcf done. Elapsed time: 0.37 minutes.
Runtime.totalMemory()=5945425920
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.IllegalArgumentException: Must specify file or stream output type.
        at htsjdk.variant.variantcontext.writer.VariantContextWriterBuilder.build(VariantContextWriterBuilder.java:424)
        at picard.vcf.SortVcf.writeSortedOutput(SortVcf.java:183)
        at picard.vcf.SortVcf.doWork(SortVcf.java:104)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:104)
```

Unless I am mistaken I am using picard at revision 3800c8218b8e4c75a4db14f97b409dbcc3dcaaa8 which is Jan 23.

Why isn't there `picard.jar --version`  or `-v` available?

**Comment by sooheelee** [comment] 2017-03-09 19:34
Hi @mmokrejs, are you a developer of Picard or just a user? If you are a user, please post your questions to the GATK forum at <http://gatkforums.broadinstitute.org/gatk/discussions>.

**Comment by yfarjoun** [comment] 2019-03-15 18:12
this seems to be a duplicate of to #630

**Closed by yfarjoun** 2019-03-15 18:12 UTC
