### ISSUE TITLE
[feature request] MergeBamAlignment: when merging from GRCh38 alignments, retain `AH:*` tag that notes which contigs were ALT-handled

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/picard#625] opened 2016-08-10 17:02 UTC
This tag is overwritten during merging by MergeBamAlignment but would be a good idea to retain.

It is in the header `@SQ` lines and denotes if a contig was ALT-handled by BWA-MEM when aligning to GRCh38.

See [Tutorial#8017](http://gatkforums.broadinstitute.org/gatk/discussion/8017)'s [section 3](http://gatkforums.broadinstitute.org/gatk/discussion/8017#3). Specifically, look at the section titled **How can I tell if a BAM was aligned with ALT-handling?** to see example screenshots of what the `AH` tag looks like.

**Comment by yfarjoun** [comment] 2016-08-10 20:22
good point soohee!! thanks for figuring this out. I was wondering why the
AH:* tags are missing.

**Comment by yfarjoun** [comment] 2016-08-11 13:40
@tfenne @nh13 @ktibbett The problem is that MBA takes the dictionary from the input reference file (or rather the nearby dictionary file). 

I would like to propose to take it from the input aligned files instead. Do you see a problem with this idea for a fix?

**Comment by tfenne** [comment] 2016-08-12 15:23
@yfarjoun I think that will create problems unfortunately.  Unless bwa is pulling through the other fields that are in the dictionary, which seems unlikely.  The resulting BAMs would likely have `@SQ` lines that lost their `MD`, `AS` and `UR` tags, which would kinda suck.  Maybe the thing to do is to merge the sequence dictionaries and take the union of tags between them?

**Comment by yfarjoun** [comment] 2016-08-12 17:36
Totally suck. Yes. it seems that bwa only picks up LN....OK. merging the
tags. Thanks for the comment.

**Comment by yfarjoun** [comment] 2017-01-17 03:50
will be fixed by #682

**Closed** 2017-01-17 19:05 UTC
