### ISSUE TITLE
Picard MarkDuplicated markered over 80% duplicates in scRNA-seq data

### ISSUE THREAD

**Issue by az7jh2** [broadinstitute/picard#1695] opened 2021-07-06 21:35 UTC
### Affected tool(s)
MarkDuplicates with `ASO=coordinate`

### Affected version(s)
Latest public release version [version 2.25.5]

### Description 
We got libraries of single cell RNA sequencing FASTQ files (10X), and mapped them to Human reference genome by STARsolo. Then we run picard MarkDuplicates tool on the BAM files and marker the duplicates

#### Steps to reproduce
We used the command
```
java -jar picard.jar MarkDuplicates \
 I=test.bam \
O=output.bam \
M=markerd_dup_measure.txt \
ASO=coordinate
```
as the output BAM files from STARsolo are already sorted by coordinate

#### Expected behavior
The duplicates percentage should below 10%

#### Actual behavior
Duplicates percentage for all libraries vary from 75% ~ 85%, which is really weird. There should not be so many duplicates. And we checked the output BAM file, and had no idea why the duplicates percentage is so high.

Can you give us any advices to fix this problem! Thanks!

**Comment by jessicaway** [comment] 2021-07-07 18:26
Hi @az7jh2, 

I don't believe this tool is intended for use with scRNA data and  I'm not sure if the high number of duplicate reads is unexpected for this data type. 

Looking at the [documentation](https://gatk.broadinstitute.org/hc/en-us/articles/360037052812-MarkDuplicates-Picard-) there is a note about setting `READ_NAME_REGEX` to `null` for RNA-seq data. That may be helpful. 

@fleharty Do you have any additional insight on this issue?

**Comment by fleharty** [comment] 2021-07-07 19:04
@jessicaway @az7jh2 

A high number of duplicate reads is not necessarily a sign of a problem with the tool.  Without looking at your data, it's not really possible for me to know if your data indeed has a lot of duplication, or if it is a problem with the tool.

I'm not familiar with running RNAseq data through these tools, so I don't know how well it does on it.

**Comment by az7jh2** [comment] 2021-07-08 02:41
@jessicaway @fleharty Thanks for the suggestions.

I re-run the picard MarkDuplicate with setting `READ_NAME_REGEX` to `null`, and the result is the same. Below is the metrics txt file for one library

```
## htsjdk.samtools.metrics.StringHeader
# MarkDuplicates INPUT=[test.bam] OUTPUT=output2.bam METRICS_FILE=markerd_dup_measure2.txt ASSUME_SORT_ORDER=coordinate READ_NAME_REGEX=null    MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 TAG_DUPLICATE_SET_MEMBERS=false REMOVE_SEQUENCING_DUPLICATES=false TAGGING_POLICY=DontTag CLEAR_DT=true DUPLEX_UMI=false ADD_PG_TAG_TO_READS=true REMOVE_DUPLICATES=false ASSUME_SORTED=false DUPLICATE_SCORING_STRATEGY=SUM_OF_BASE_QUALITIES PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 MAX_OPTICAL_DUPLICATE_SET_SIZE=300000 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
## htsjdk.samtools.metrics.StringHeader
# Started on: Wed Jul 07 21:23:01 EDT 2021

## METRICS CLASS	picard.sam.DuplicationMetrics
LIBRARY	UNPAIRED_READS_EXAMINED	READ_PAIRS_EXAMINED	SECONDARY_OR_SUPPLEMENTARY_RDS	UNMAPPED_READS	UNPAIRED_READ_DUPLICATES	READ_PAIR_DUPLICATES	READ_PAIR_OPTICAL_DUPLICATES	PERCENT_DUPLICATION	ESTIMATED_LIBRARY_SIZE
Unknown Library	51089210	0	5730221	0	41227179	0	0	0.806965
```

And the first 5 records of the output BAM file as below (already sorted by coordinate)

```
D00536:462:H22GJBCX2:2:2113:3820:2944	256	chr1	14059	0	98M	*	0	0	AGTCGATGGCACCTCCCTCCCTCTCAACCACTTGAGCAAACTCCAAGACATCTTCTACCCCAACACCAGCAATTGTGCCAAGGGCCATTAGGCTCTCA	DADDDIIIIHHIIIIIIHHEHHHHHHIIIIIHGECCEIFCHHIHGIHIIHIIIIIIIIHHHIIIIIFEHIIHHE@EGEHIHIIHGHHHEHH1CC@HHC	CB:Z:GACAGAGAGTGTCTCA  UB:Z:TTTTGTAGTG	PG:Z:MarkDuplicates	NH:i:6	HI:i:3	nM:i:0	sM:i:0	sQ:Z:DDDDDIIHIHCEHHHHHIIIFHIIII	CR:Z:GACAGAGAGTGTCTCA	UR:Z:TTTTGTAGTG	AS:i:96	sS:Z:GACAGAGAGTGTCTCATTTTGTAGTG
D00536:462:H22GJBCX2:2:1206:6591:94479	16	chr1	14367	1	57M	*	0	0	CACAGCTAGAGATCCTTTATTTAAAGCACACTGTTGGTTTCTGCTCAGTTCTTTATT	<<<11@D11111<11GHH@HED1111<1111HCHG<EIHG<D11D<<@HF1IIH@HC	CB:Z:ACTGCTCAGAATGTGT	UB:Z:TGATCAGAGT	PG:Z:MarkDuplicates	NH:i:4	HI:i:1	nM:i:1	sM:i:0	sQ:Z:DDDDCIIIIHGIIIIHIIIIIIIIIH	CR:Z:ACTGCTCAGAATGTGT	UR:Z:TGATCAGAGT	AS:i:54	sS:Z:ACTGCTCAGAATGTGTTGATCAGAGT
D00536:462:H22GJBCX2:2:2201:11740:55101	272	chr1	14388	0	98M	*	0	0	AAAAGCACACTGTTGGTTTCTGCTCAGTTCTTTATTGATTGGTGTGCCGTTTTCTCTGGAAGCCTCTTAAGAACACAGTGGCGCAGGCTGGGTGGAGC	IIHHGIIIIHIHHEFHIIHIIIIIHIHEIIHECHEHHHHHHGDDCHECEHIHHHEHHHIIIIIIGIHHEIIIHIHIIHIIIIIGIIIHHHFHHADBCD	CB:Z:TGGGCGTCACATTCGA  UB:Z:GGGATGACGT	PG:Z:MarkDuplicates	NH:i:5	HI:i:4	nM:i:0	sM:i:0	sQ:Z:DDDDDHIIIIIIIIIHHHIEHIIIII	CR:Z:TGGGCGTCACATTCGA	UR:Z:GGGATGACGT	AS:i:96	sS:Z:TGGGCGTCACATTCGAGGGATGACGT
D00536:462:H22GJBCX2:2:1210:11038:86056	272	chr1	14388	0	98M	*	0	0	AAAAGCACACTGTTGGTTTCTGCTCAGTTCTTTATTGATTGGTGTGCCGTTTTCTCTGGAAGCCTCTTAAGAACACAGTGGCGCAGGCTGGGTGGAGC	IIHHIHIIHHEIHHHHHCGIHIHHIIIHGDEHEIHFHIIHIHFHHIHHHHF?FHIIHHFHGGHF1DHHIIIHHIIIIIIIGIGHHHHIIIHHHDDCDD	CB:Z:TGGGCGTCACATTCGA  UB:Z:GGGATGACGT	PG:Z:MarkDuplicates	NH:i:5	HI:i:4	nM:i:0	sM:i:0	sQ:Z:DDDADEHIIIIIIGHHHDICGHIIHG	CR:Z:TGGGCGTCACATTCGA	UR:Z:GGGATGACGT	AS:i:96	sS:Z:TGGGCGTCACATTCGAGGGATGACGT
D00536:462:H22GJBCX2:1:1114:21035:31177	272	chr1	14402	0	49M	*	0	0	GGTTTCTGCTCAGTTCTTTATTGATTGGTGTGCCGTTTTCTCTGGAAGC	CEHIHCG?CF<?HIHFHIHCHHGEIIHIIIHE0DIIHIIHHGF<<0?BD	CB:Z:TCATTTGGTACAGCAG	UB:Z:GACCTGGGAT	PG:Z:MarkDuplicates	NH:i:9	HI:i:6	nM:i:0	sM:i:0	sQ:Z:BDDDDHIIIIIIIIIIIIIIIGIIII	CR:Z:TCATTTGGTACAGCAG	UR:Z:GACCTGGGAT	AS:i:48	sS:Z:TCATTTGGTACAGCAGGACCTGGGAT
```

I still think there are too many duplicates are markered, For example, read 1 is the only read mapping to chr1:14059, but it's still markered as duplicated.

Now there has been some methods trying to do SNP calling from scRNA-seq data (such as [SSrGE](https://www.nature.com/articles/s41467-018-07170-5), *nature comunications*, 2018). It use GATK to do the SNP calling, and used picard MarkDuplicates in their pipeline (see the [flowchart](https://github.com/lanagarmire/SSrGE/blob/master/README_snv_calling.md)). So I guess picard MarkDuplicates still can be used for scRNA-seq data though it may not be the best tool. But I really do not know how so many duplicates come up and need your helps. 

Thanks again!

**Comment by yfarjoun** [comment] 2021-07-08 15:12
So, a few options to help you investigate the issue:

1. You can run MarkDupllicates with an option (TAG_DUPLICATE_SET_MEMBERS=true & TAGGING_POLICY=all ) to label the duplicate reads with the reason they are duplicate (optical/library) and the representative read that they are a duplicate of. This can further assist in your investigation.

2. You can run SortSam using the sort-order "duplicate" which will put the read in the order that they are collected for duplicate marking. This will put reads that are duplicates of each other (according to picard) close together so you can then understand why they are marked.

**Comment by az7jh2** [comment] 2021-07-08 18:58
@yfarjoun Thanks for the advices.

I tried the below command

```
java -jar picard.jar MarkDuplicates \
I=test.bam \
O=output.bam \
M=markerd_dup_measure.txt \
ASO=coordinate \
READ_NAME_REGEX=null \
TAG_DUPLICATE_SET_MEMBERS=true \
TAGGING_POLICY=All
```

Below is the output of first 5 reads in the output BAM file.

```
D00536:462:H22GJBCX2:2:2113:3820:2944	256	chr1	14059	0	98M	*	0	0	AGTCGATGGCACCTCCCTCCCTCTCAACCACTTGAGCAAACTCCAAGACATCTTCTACCCCAACACCAGCAATTGTGCCAAGGGCCATTAGGCTCTCA	DADDDIIIIHHIIIIIIHHEHHHHHHIIIIIHGECCEIFCHHIHGIHIIHIIIIIIIIHHHIIIIIFEHIIHHE@EGEHIHIIHGHHHEHH1CC@HHC	CB:Z:GACAGAGAGTGTCTCA	UB:Z:TTTTGTAGTG	PG:Z:MarkDuplicates	NH:i:6	HI:i:3	nM:i:0	sM:i:0sQ:Z:DDDDDIIHIHCEHHHHHIIIFHIIII	CR:Z:GACAGAGAGTGTCTCA	UR:Z:TTTTGTAGTG	AS:i:96	sS:Z:GACAGAGAGTGTCTCATTTTGTAGTG
D00536:462:H22GJBCX2:2:1206:6591:94479	16	chr1	14367	1	57M	*	0	0	CACAGCTAGAGATCCTTTATTTAAAGCACACTGTTGGTTTCTGCTCAGTTCTTTATT	<<<11@D11111<11GHH@HED1111<1111HCHG<EIHG<D11D<<@HF1IIH@HC	CB:Z:ACTGCTCAGAATGTGT	UB:Z:TGATCAGAGTPG:Z:MarkDuplicates	NH:i:4	HI:i:1	nM:i:1	sM:i:0	sQ:Z:DDDDCIIIIHGIIIIHIIIIIIIIIH	CR:Z:ACTGCTCAGAATGTGT	UR:Z:TGATCAGAGT	AS:i:54sS:Z:ACTGCTCAGAATGTGTTGATCAGAGT
D00536:462:H22GJBCX2:2:2201:11740:55101	272	chr1	14388	0	98M	*	0	0	AAAAGCACACTGTTGGTTTCTGCTCAGTTCTTTATTGATTGGTGTGCCGTTTTCTCTGGAAGCCTCTTAAGAACACAGTGGCGCAGGCTGGGTGGAGC	IIHHGIIIIHIHHEFHIIHIIIIIHIHEIIHECHEHHHHHHGDDCHECEHIHHHEHHHIIIIIIGIHHEIIIHIHIIHIIIIIGIIIHHHFHHADBCD	CB:Z:TGGGCGTCACATTCGA	UB:Z:GGGATGACGT	PG:Z:MarkDuplicates	NH:i:5	HI:i:4	nM:i:0	sM:i:0sQ:Z:DDDDDHIIIIIIIIIHHHIEHIIIII	CR:Z:TGGGCGTCACATTCGA	UR:Z:GGGATGACGT	AS:i:96	sS:Z:TGGGCGTCACATTCGAGGGATGACGT
D00536:462:H22GJBCX2:2:1210:11038:86056	272	chr1	14388	0	98M	*	0	0	AAAAGCACACTGTTGGTTTCTGCTCAGTTCTTTATTGATTGGTGTGCCGTTTTCTCTGGAAGCCTCTTAAGAACACAGTGGCGCAGGCTGGGTGGAGC	IIHHIHIIHHEIHHHHHCGIHIHHIIIHGDEHEIHFHIIHIHFHHIHHHHF?FHIIHHFHGGHF1DHHIIIHHIIIIIIIGIGHHHHIIIHHHDDCDD	CB:Z:TGGGCGTCACATTCGA	UB:Z:GGGATGACGT	PG:Z:MarkDuplicates	NH:i:5	HI:i:4	nM:i:0	sM:i:0sQ:Z:DDDADEHIIIIIIGHHHDICGHIIHG	CR:Z:TGGGCGTCACATTCGA	UR:Z:GGGATGACGT	AS:i:96	sS:Z:TGGGCGTCACATTCGAGGGATGACGT
D00536:462:H22GJBCX2:1:1114:21035:31177	272	chr1	14402	0	49M	*	0	0	GGTTTCTGCTCAGTTCTTTATTGATTGGTGTGCCGTTTTCTCTGGAAGC	CEHIHCG?CF<?HIHFHIHCHHGEIIHIIIHE0DIIHIIHHGF<<0?BD	CB:Z:TCATTTGGTACAGCAG	UB:Z:GACCTGGGAT	PG:Z:MarkDuplicates	NH:i:9	HI:i:6	nM:i:0	sM:i:0	sQ:Z:BDDDDHIIIIIIIIIIIIIIIGIIII	CR:Z:TCATTTGGTACAGCAG	UR:Z:GACCTGGGAT	AS:i:48	sS:Z:TCATTTGGTACAGCAGGACCTGGGAT
```

But the in the output BAM file, I didn't see the DS and DI tag for the reads marked as duplicates. Do you think I use the options in a wrong way?

**Comment by yfarjoun** [comment] 2021-07-08 20:08
I don't see any duplicate reads in your example....I see non-primary
alignments (flag 256) but not duplicate (flag 1024) (see
https://broadinstitute.github.io/picard/explain-flags.html)

could you subset on flag 1024 (using samtools view perhaps) and include a
few reads from there?

**Comment by az7jh2** [comment] 2021-07-12 21:22
@yfarjoun sorry I misunderstood the duplicates identication of Picard MarkDuplicates. I thought reads with the tag `PG:Z:MarkDuplicates`  are marked as duplicates by Picard, but actually this is not true, and every read will have this tag.

I sort the output BAM file from Picard MarkDuplicates by SortSam with the option `SORT_ORDER=duplicate`. And below is the first 5 reads from the sorted BAM file:

```
D00536:462:H22GJBCX2:1:1216:13637:89218	1040	chr1	14457	0	97M	*	0	0	AGAACACAGTGGCGCAGGCTGGGTGGAGCCGTCCCCCCATGGAGCACAGGCAGACAGAAGTCCCCACCCCAGCTGTGTGGCCTCAGGCCAGCCTTCC	AEEB.HHFE<G?-;..EHFHE/F<</EHECCHIHIIHFC1F<1EHHEG@FGHHEHEEHECCHDF/DHIHH@HFEGFD<<GC11@C?IIHIHIDD@B@	CB:Z:TCTTCGGCACCACCAG	UB:Z:ACCGCATTGT	PG:Z:MarkDuplicates	NH:i:6	HI:i:1	nM:i:2	sM:i:0	sQ:Z:?0BD@CEC?EC1CE1<DECHDCHC@<	CR:Z:TCTTCGGCACCACCAG	UR:Z:ACCGCATTGT	AS:i:91	sS:Z:TCTTCGGCACCACCAGACCGCATTGT	DT:Z:LB
D00536:462:H22GJBCX2:1:2115:3321:59848	1040	chr1	14481	0	93M1S	*	0	0	GGAGCCGTCCCCCCATGGAGCACAGGCGGACAGAAGTCCCCGCCCCAGCTGTGTGGCCTCAAGCCAGCATTCCGCTCCTTGAAGCTGGTCTCCT	A:8?:--8D/0?EGD1F<11111C0<<11<1<111/?C<</<<01111GHHFD11<111/110111111/<//1111HEGD11FCC11D0D<00	CB:Z:TGGTTCCTCACCAGGC	UB:Z:TGAAGAGAGT	PG:Z:MarkDuplicates	NH:i:6	HI:i:1	nM:i:2	sM:i:0	sQ:Z:<D?D@FFEHIE?HHFH<<FCE?<C<<	CR:Z:TGGTTCCTCACCAGGC	UR:Z:TGAAGAGAGT	AS:i:87	sS:Z:TGGTTCCTCACCAGGCTGAAGAGAGT	DT:Z:LB
D00536:462:H22GJBCX2:1:1114:2891:85232	1040	chr1	14478	0	98M	*	0	0	GGTGGAGCCGTCCCCCCATGGTGCACAGGCAGACAGAAGTCCCCGCCCCAGCTGTGTGGCCTCAAGCCAGCCTTCCGCTTCTTGAAGCTTGTCTCCAC	B/FE:::///D//011<1<111111<11<<11111111/<////0/0<1111HFH@<1111</11<01110/F<</11D1?GD<11<1D1HG<D0<0<	CB:Z:GAAATGAAGCTAGCCC	UB:Z:GTAATTAGAT	PG:Z:MarkDuplicates	NH:i:6	HI:i:1	nM:i:3	sM:i:0	sQ:Z:DBDDDHIEHIHHIHIIIHIIIIIGGH	CR:Z:GAAATGAAGCTAGCCC	UR:Z:GTAATTAGAT	AS:i:90	sS:Z:GAAATGAAGCTAGCCCGTAATTAGAT	DT:Z:LB
D00536:462:H22GJBCX2:2:1114:4014:41607	1040	chr1	14478	0	96M2S	*	0	0	GGTGGAGCCGTCCCCCCATGGAGCACAGGCAGACAGAAGTCCCCGCCCCAGCTGTGTGGCCTCAGGCCAGCCTTCCGCTCCTTGAAGCTGGTCTCCGC	HFG@D<HHHD:IIIHHGHGHEGF1HEHHCCGD<?FHHFC<H<HHHHHEEHHHDHHHFHHECEHFHDHHHHECCHHCIHHIGIHHFC?CHEHIICDBDD	CB:Z:AACTGGTCAGGCGATA	UB:Z:ATGAGAGTCG	PG:Z:MarkDuplicates	NH:i:6	HI:i:1	nM:i:1	sM:i:0	sQ:Z:DDADBIHHIGCHHHIEHEHCGCG@FH	CR:Z:AACTGGTCAGGCGATA	UR:Z:ATGAGAGTCG	AS:i:92	sS:Z:AACTGGTCAGGCGATAATGAGAGTCG	DT:Z:LB
D00536:462:H22GJBCX2:2:2216:16110:85184	1040	chr1	14484	0	1S97M	*	0	0	GGCCGTCCCCCCATGGAGCACAGGCAGACAGAAGTCCCCGCCCCAGCTGTGTGGCCTCAGGCCAGCCTTCCGCTCCTTGATGCTGGTTTCCGCATAGT	8--8D:-.00C0?HC<<11C?EC<11<1<1<1<<<////0/<<1<11G<H@G1<11<11<0<1110/EC</11D11FD<11<<D11</</01<000@<	CB:Z:TTAACTCCATATGGTC	UB:Z:TGAATGCGCA	PG:Z:MarkDuplicates	NH:i:6	HI:i:1	nM:i:5	sM:i:0	sQ:Z:BBDBDIIIIIHEHCGGHFEGHEHIHH	CR:Z:TTAACTCCATATGGTC	UR:Z:TGAATGCGCA	AS:i:85	sS:Z:TTAACTCCATATGGTCTGAATGCGCA	DT:Z:LB
```
In the results, I can see the `DT:Z:LB` tag which indicates these are library/PCR-generated duplicates (LB), but don't see the DS and DI tags.

Do you think there are really so many duplicates in this library?

**Comment by az7jh2** [comment] 2021-07-19 03:31
@jessicaway @fleharty @yfarjoun 

I looked more into the Picard Markduplicates results, and I think the results are appropriate. 

As shown in this figure, left panel shows using Picard Markduplicates without considering the cell barcode and UMI of reads. Many of the reads are marked as duplicates and only one read are kept at the position chr1 : 954,00 bp (colored by pink in left top panel) though they are with different cell barcodes+UMIs (colored with different colors in left bottom panel, and they are two different cell barcodes+UMIs). But when considering the cell barcode and UMI (using it for the option `BARCODE_TAG`), there will be two non-duplicate reads (right top panel) for the two cell barcodes+UMIs (right bottom panel).
![Compare](https://user-images.githubusercontent.com/50506882/126096135-21062d6f-2c7a-4881-900f-562d0ec6ae58.jpg)

As for the high duplicate rate, it's reasonable to have a high duplicate rate for RNA-seq data as many reads may map to the high expressed genes. For this library, the duplicate rate is 80%, and when considering the cell barcodes+UMIs, the duplicate rate is 49%.

Thanks for all your helps. And I think you can close this issue now.

**Comment by fleharty** [comment] 2021-07-19 17:34
@az7jh2 Glad to hear the results look appropriate.  Thanks for reaching out to close this!

**Closed by fleharty** 2021-07-19 17:34 UTC
